### ISSUE TITLE
Planetary Computer Hub error mounting volume, expired token

### ISSUE THREAD

**Issue by Websy-A** [microsoft/PlanetaryComputer#343]
Hello,
I'm trying to spin up a CPU node and getting this 401 error:

-- RESPONSE 401: 401 Unauthorized ERROR CODE: ExpiredAuthenticationToken -------------------------------------------------------------------------------- { "error": { "code": "ExpiredAuthenticationToken", "message": "The access token expiry UTC time '5/13/2024 6:05:58 PM' is earlier than current UTC time '5/13/2024 8:21:34 PM'." } } ----------

A colleague is getting the same error. 
Is this something on the backend?

Thanks.

**Comment by TomAugspurger** [comment]
We saw that over the weekend (https://github.com/microsoft/PlanetaryComputer/discussions/342) but it was resolved earlier today. Apparently it's returned :/

> Is this something on the backend?

Yes. I don't think there's anything you can do on your side.

**Comment by Websy-A** [comment]
Still happening for me right now though, so not resolved unfortunately.

**Comment by TomAugspurger** [comment]
I'm able to successfully start a notebook server now, so it seems to have resolved itself (at least for now). I'll close this to consolidate the discussion in https://github.com/microsoft/PlanetaryComputer/discussions/342.
